# Generated by Django 5.1.1 on 2024-10-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_categoria_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="area_saber",
        ),
        migrations.RemoveField(
            model_name="disciplinacurso",
            name="carga_horaria",
        ),
        migrations.RemoveField(
            model_name="disciplinacurso",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="disciplinacurso",
            name="periodo",
        ),
        migrations.AddField(
            model_name="disciplina",
            name="curso",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.curso"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tipoavaliacao",
            name="carga_horaria",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tipoavaliacao",
            name="curso",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.curso"
            ),
        ),
    ]
