# Generated by Django 5.1.1 on 2024-10-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_periodo_remove_disciplina_area_saber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipoavaliacao",
            name="carga_horaria",
        ),
        migrations.RemoveField(
            model_name="tipoavaliacao",
            name="curso",
        ),
        migrations.AddField(
            model_name="disciplinacurso",
            name="carga_horaria",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disciplinacurso",
            name="curso",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="app.curso"
            ),
            preserve_default=False,
        ),
    ]
