from django.contrib import admin
from .models import Categoria, Produto, Pessoa, Cidade, Ocupacao, Instituicao, AreaSaber, Curso, PeriodoCurso, Disciplina, Matricula, Avaliacao, Frequencia, Turma, Ocorrencia, DisciplinaCurso, TipoAvaliacao

admin.site.register(Categoria)
admin.site.register(Produto)
admin.site.register(Pessoa)
admin.site.register(Cidade)
admin.site.register(Ocupacao)
admin.site.register(Instituicao)
admin.site.register(AreaSaber)
admin.site.register(Curso)
admin.site.register(PeriodoCurso)
admin.site.register(Disciplina)
admin.site.register(Matricula)
admin.site.register(Avaliacao)
admin.site.register(Frequencia)
admin.site.register(Turma)
admin.site.register(Ocorrencia)
admin.site.register(DisciplinaCurso)
admin.site.register(TipoAvaliacao)